use async_trait::async_trait;
use serde::{Deserialize, Serialize};

use crate::context::ToolContext;

/// Permission gate for a tool invocation. Read-tools run silently, Write
/// and Exec require approval (or an allowlist match).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Permission {
    /// Pure read of local state or trusted resources. No approval needed.
    Read,
    /// Writes to local state (files, memory, DB). Approval gated.
    Write,
    /// Executes external processes or remote effects. Approval gated.
    Exec,
}

impl Permission {
    pub fn needs_approval(&self) -> bool {
        !matches!(self, Permission::Read)
    }
}

/// Result of a tool invocation. `trustworthy = false` flags content that
/// came from an untrusted source (web fetch, untrusted files, MCP servers
/// of unknown origin); the agent loop wraps such outputs in a
/// `<tool_result trustworthy="false">` envelope before feeding them back
/// to the model (Phase 1.10).
#[derive(Debug, Clone)]
pub struct ToolOutput {
    pub content: String,
    pub is_error: bool,
    pub trustworthy: bool,
}

impl ToolOutput {
    pub fn ok(content: impl Into<String>) -> Self {
        Self {
            content: content.into(),
            is_error: false,
            trustworthy: true,
        }
    }

    pub fn untrusted(content: impl Into<String>) -> Self {
        Self {
            content: content.into(),
            is_error: false,
            trustworthy: false,
        }
    }

    pub fn error(message: impl Into<String>) -> Self {
        Self {
            content: message.into(),
            is_error: true,
            trustworthy: true,
        }
    }
}

#[derive(Debug, thiserror::Error)]
pub enum ToolError {
    #[error("invalid arguments: {0}")]
    InvalidArgs(String),

    #[error("denied by user")]
    Denied,

    #[error("cancelled")]
    Cancelled,

    #[error("io: {0}")]
    Io(String),

    #[error("transport: {0}")]
    Transport(String),

    #[error("internal: {0}")]
    Internal(String),
}

/// Object-safe tool trait. Concrete implementations parse the JSON args
/// into their own typed struct internally. Each tool also publishes a
/// JSON-Schema for its args via [`Self::schema`], generated with
/// `schemars` at the impl site.
#[async_trait]
pub trait Tool: Send + Sync {
    /// Stable identifier used by the LLM in tool-call payloads.
    fn name(&self) -> &'static str;

    /// Single-sentence description plus optional example. Goes into the
    /// tool-list segment of the prompt — keep it short and in the
    /// LLM-readable register.
    fn description(&self) -> &'static str;

    fn permission(&self) -> Permission;

    /// JSON Schema for the input args. Generated by the impl via
    /// `schemars::schema_for!(MyArgs)`.
    fn schema(&self) -> serde_json::Value;

    /// Execute the tool. Implementations must check `ctx.cancel` before
    /// long operations and surface `ToolError::Cancelled` promptly.
    async fn invoke(
        &self,
        args: serde_json::Value,
        ctx: &ToolContext,
    ) -> Result<ToolOutput, ToolError>;
}
